@hostname = http://localhost:3000/api
@resource = auth


### TESTING PRIVATE ROUTE (me)
GET {{hostname}}/{{resource}}/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3NTg0OTBkYS03N2ZmLTRhOWUtYTBjZC0zMWRmMjE2MTgwOGYiLCJpYXQiOjE2NTkwOTIxNzMsImV4cCI6MTY1OTA5MjIzM30.nEBMVsLlLsYuoEd5t0ogROULooi5WPLzwK-548jP5rU

### REGISTER
POST {{hostname}}/{{resource}}/register HTTP/1.1
content-type: application/json

{
    "email": "jhon1@mail.com",
    "password": "Abc123!",
    "fullName": "John Doe"
}

### LOGIN
POST {{hostname}}/{{resource}}/login HTTP/1.1
content-type: application/json

{
    "email": "jhon1@mail.com",
    "password": "Abc123!"
}

### UPDATE
PATCH {{hostname}}/{{resource}}/106cce85-8b63-4d0c-97ef-c49544cc1d16 HTTP/1.1
content-type: application/json

{
    "email": "jhon@mail.com",
    "password": "Abc123!",
    "fullName": "John Doe"
}

### DELETE
DELETE {{hostname}}/{{resource}}/1fb79a73-8d4f-41c0-b33e-7390859de571 HTTP/1.1
content-type: application/json