@hostname = http://localhost:3000/api
@resource = products

### GET ALL
GET {{hostname}}/{{resource}}?limit=5 HTTP/1.1

### GET ONE
GET {{hostname}}/{{resource}}/a HTTP/1.1

### CREATE
POST {{hostname}}/{{resource}} HTTP/1.1
content-type: application/json

{
    "title": "Product 3",
    "description": "This is a product",
    "price": 200,
    "sizes": [
        "S",
        "M",
        "L"
    ],
    "slug": "ola k ace",
    "gender": "women"
}

### UPDATE
PATCH {{hostname}}/{{resource}}/62de61671d322db089ffb39d HTTP/1.1
content-type: application/json

{
    "title": "Product 1",
    "description": "This is a product",
    "price": 100,
    "sizes": [
        "S",
        "M",
        "L"
    ],
    "slug": "product-1",
    "gender": "men"
}

### DELETE
DELETE {{hostname}}/{{resource}}/1fb79a73-8d4f-41c0-b33e-7390859de571 HTTP/1.1
content-type: application/json