@hostname = http://localhost:3000/api
@resource = products

### GET ALL
GET {{hostname}}/{{resource}}?limit=100 HTTP/1.1

### GET ONE
GET {{hostname}}/{{resource}}/106cce85-8b63-4d0c-97ef-c49544cc1d16 HTTP/1.1

### CREATE
POST {{hostname}}/{{resource}} HTTP/1.1
content-type: application/json

{
    "title": "Product 11",
    "description": "This is a product",
    "price": 200.99,
    "sizes": [
        "S",
        "M",
        "L"
    ],
    "tags": ["hi"],
    "gender": "women",
    "images": ["img1", "img2"]
}

### UPDATE
PATCH {{hostname}}/{{resource}}/78f7966d-8608-46c5-ad9d-94fe0033cd6f HTTP/1.1
content-type: application/json

{
    "description": "This is a product",
    "price": 100,
    "sizes": [
        "S",
        "M",
        "L"
    ],
    "tags":["shirt", "tag"],
    "gender": "unisex"
}

### DELETE
DELETE {{hostname}}/{{resource}}/1fb79a73-8d4f-41c0-b33e-7390859de571 HTTP/1.1
content-type: application/json