@hostname = http://localhost:3000/api
@resource = seed

### POPULATE DB WITH DATA
GET {{hostname}}/{{resource}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3NTg0OTBkYS03N2ZmLTRhOWUtYTBjZC0zMWRmMjE2MTgwOGYiLCJpYXQiOjE2NTkxMDEzODMsImV4cCI6MTY1OTEwMTQ0M30.62HKSsezhsFb5XNIj0zKOLt4iO0ZQBQ-DLBplFj6CWk